# Generated by Django 6.0.2 on 2026-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
