"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured

from .env import env_bool, env_int, env_list, env_str, load_local_env

load_local_env()

from .confiq import DATABASES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DEBUG = env_bool('DJANGO_DEBUG', default=True)

if DEBUG:
    SECRET_KEY = env_str('DJANGO_SECRET_KEY', default='django-insecure-dev-only-change-me')
else:
    SECRET_KEY = env_str('DJANGO_SECRET_KEY', required=True)

default_allowed_hosts = ['localhost', '127.0.0.1']
render_external_hostname = env_str('RENDER_EXTERNAL_HOSTNAME', default='')
if render_external_hostname:
    default_allowed_hosts.append(render_external_hostname)

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    default=default_allowed_hosts,
)
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set when DJANGO_DEBUG is false.')

APPS = [
    'user',
    'brand',
    'banner_images',
    'ingredient',
    'categorie',
    'skin_concern',
    'hair_concern',
    'product',
    'product_type',
    'send_otp',
    'secure_derma',
]

local_cors_origins = [
    'http://localhost:38373',
    'http://localhost:4201',
    'http://localhost:4200',
    'http://127.0.0.1:4200',
    'https://secure-derma-admin.vercel.app',
]
CORS_ALLOWED_ORIGINS = [*local_cors_origins, *env_list('CORS_ALLOWED_ORIGINS')]
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(CORS_ALLOWED_ORIGINS))
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

USE_S3 = env_bool('AWS_S3_ENABLED', default=False)
AWS_S3_REGION_NAME = env_str('AWS_REGION', default='')
AWS_STORAGE_BUCKET_NAME = env_str('AWS_S3_BUCKET', default='')
AWS_S3_CUSTOM_DOMAIN = env_str('AWS_S3_CUSTOM_DOMAIN', default='')
AWS_QUERYSTRING_AUTH = env_bool('AWS_QUERYSTRING_AUTH', default=True)
AWS_QUERYSTRING_EXPIRE = env_int('AWS_QUERYSTRING_EXPIRE', 3600)
AWS_S3_FILE_OVERWRITE = env_bool('AWS_S3_FILE_OVERWRITE', default=False)
AWS_DEFAULT_ACL = None
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': env_str('AWS_S3_CACHE_CONTROL', default='max-age=86400'),
}

if USE_S3:
    if not AWS_S3_REGION_NAME:
        raise ImproperlyConfigured('AWS_REGION must be set when AWS_S3_ENABLED is true.')
    if not AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured('AWS_S3_BUCKET must be set when AWS_S3_ENABLED is true.')

    aws_access_key_id = env_str('AWS_ACCESS_KEY_ID', default='')
    aws_secret_access_key = env_str('AWS_SECRET_ACCESS_KEY', default='')
    if aws_access_key_id:
        AWS_ACCESS_KEY_ID = aws_access_key_id
    if aws_secret_access_key:
        AWS_SECRET_ACCESS_KEY = aws_secret_access_key

    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN.rstrip('/')}/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/"

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    MEDIA_URL = '/media/'
    default_media_root = BASE_DIR / 'media'
    MEDIA_ROOT = Path(env_str('MEDIA_ROOT', default=str(default_media_root))).resolve()

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
] + APPS

if USE_S3:
    INSTALLED_APPS.append('storages')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env_int('JWT_ACCESS_TOKEN_MINUTES', 15)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int('JWT_REFRESH_TOKEN_DAYS', 30)),
}

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)

AUTH_USER_MODEL = 'user.User'

SENDGRID_API_KEY = env_str('SENDGRID_API_KEY', default='')
SENDGRID_FROM_EMAIL = env_str('SENDGRID_FROM_EMAIL', default='')
SENDGRID_FROM_NAME = env_str('SENDGRID_FROM_NAME', default='Secure Derma')
DEFAULT_FROM_EMAIL = env_str('DEFAULT_FROM_EMAIL', default=SENDGRID_FROM_EMAIL or 'noreply@securederma.local')
