# Generated by Django 6.0.2 on 2026-02-27 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='producttype/')),
                ('show_banner', models.BooleanField(default=False)),
                ('show_home', models.BooleanField(default=False)),
                ('product_type', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categories')),
            ],
        ),
    ]
