# Generated by Django 6.0.2 on 2026-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('type', models.CharField(choices=[('main_image', 'Main Image'), ('landing_page', 'Landing Page'), ('why_secure_derma', 'Why Secure Derma'), ('skin_thumbnail', 'Skin Thumbnail'), ('skin_banner', 'Skin Banner'), ('hair_thumbnail', 'Hair Thumbnail'), ('hair_banner', 'Hair Banner'), ('supplement_thumbnail', 'Supplement Thumbnail'), ('supplement_banner', 'Supplement Banner'), ('pediatric', 'Pediatric'), ('pediatric_banner', 'Pediatric Banner'), ('shop_all', 'Shop All')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
