# Generated by Django 6.0.2 on 2026-03-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_images', '0002_alter_imagefile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='type',
            field=models.CharField(choices=[('main_image', 'Main Image'), ('landing_page', 'Landing Page'), ('why_secure_derma', 'Why Secure Derma'), ('skin_thumbnail', 'Skin Thumbnail'), ('skin-care', 'Skin Banner'), ('hair_thumbnail', 'Hair Thumbnail'), ('hair-care', 'Hair Banner'), ('supplement_thumbnail', 'Supplement Thumbnail'), ('supplements', 'Supplement Banner'), ('pediatric_thumbnail', 'Pediatric'), ('pediatric', 'Pediatric Banner'), ('all', 'Shop All')], max_length=50),
        ),
    ]
