# Generated by Django 6.0.2 on 2026-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner_images', '0003_alter_imagefile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
