# Generated by Django 6.0.2 on 2026-02-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_otp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
