# Generated by Django 6.0.2 on 2026-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_otp', '0002_otprecord_resend_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='lock_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
