# Generated by Django 6.0.2 on 2026-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='brands/')),
                ('brand_description', models.TextField(blank=True, null=True)),
                ('show_brand', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_top_brand', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
