# Generated by Django 6.0.2 on 2026-02-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('categorie', '0001_initial'),
        ('hair_concern', '0001_initial'),
        ('ingredient', '0001_initial'),
        ('product_type', '0001_initial'),
        ('skin_concern', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='products/thumbnail/')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='products/hover/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('key_benefits', models.JSONField(blank=True, default=list)),
                ('key_ingredients', models.JSONField(blank=True, default=list)),
                ('how_to_use', models.JSONField(blank=True, default=list)),
                ('trending_product', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.categories')),
                ('hair_concern', models.ManyToManyField(blank=True, to='hair_concern.hairconcerns')),
                ('ingredient', models.ManyToManyField(blank=True, to='ingredient.ingredients')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_type.producttype')),
                ('skin_concern', models.ManyToManyField(blank=True, to='skin_concern.skinconcerns')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_weight', models.CharField(max_length=50)),
                ('weight_type', models.CharField(max_length=50)),
                ('combo', models.IntegerField(default=1)),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('available_stock_count', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/reviews/')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.productreview')),
            ],
        ),
    ]
