import {
  ArchiveRestoreIcon,
  ArrowLeft,
  AsteriskIcon,
  AwardIcon,
  BellIcon,
  BinaryIcon,
  BotMessageSquare,
  BoxesIcon,
  BoxIcon,
  BrushIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartColumnIcon,
  ChartLineIcon,
  ChartSplineIcon,
  CheckCheckIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  Columns2Icon,
  Columns3Icon,
  Columns4Icon,
  CopyIcon,
  DownloadIcon,
  EllipsisIcon,
  EllipsisVerticalIcon,
  ExpandIcon,
  EyeIcon,
  FileTextIcon,
  FileUpIcon,
  FlaskConicalIcon,
  FlowerIcon,
  FolderOpenIcon,
  FunnelIcon,
  GemIcon,
  HammerIcon,
  HeartIcon,
  HelpCircleIcon,
  HistoryIcon,
  ImagesIcon,
  ImportIcon,
  IndianRupeeIcon,
  InfoIcon,
  KeyIcon,
  KeyRound,
  LayoutGridIcon,
  LogOutIcon,
  MailIcon,
  MapPinIcon,
  MenuIcon,
  MessageSquareText,
  MinusIcon,
  MoonIcon,
  NotebookPenIcon,
  PackageCheckIcon,
  PackageIcon,
  PackageOpenIcon,
  PauseIcon,
  PencilIcon,
  PenToolIcon,
  PlayIcon,
  PlusIcon,
  PresentationIcon,
  RectangleHorizontalIcon,
  RocketIcon,
  RotateCcwIcon,
  RulerIcon,
  SaveIcon,
  ScaleIcon,
  SearchIcon,
  SendIcon,
  ServerCog,
  SettingsIcon,
  Share2Icon,
  ShareIcon,
  ShoppingBagIcon,
  SlashIcon,
  SlidersIcon,
  SparkleIcon,
  SparklesIcon,
  SquareIcon,
  SquarePen,
  StarIcon,
  StickerIcon,
  StoreIcon,
  SunIcon,
  SunMoonIcon,
  ThumbsDown,
  ThumbsDownIcon,
  ThumbsUp,
  ThumbsUpIcon,
  TrashIcon,
  TrendingUpIcon,
  TrophyIcon,
  TruckIcon,
  UploadIcon,
  UserCheckIcon,
  UserCogIcon,
  UserIcon,
  UserPenIcon,
  UserPlusIcon,
  UserRoundCheckIcon,
  UserRoundXIcon,
  UsersIcon,
  UsersRoundIcon,
  VideoIcon,
  WandSparklesIcon,
  WarehouseIcon,
  WeightIcon,
  WholeWordIcon,
  XIcon
} from 'lucide-angular';

export const Icons = {
  theme: {
    light: SunIcon,
    dark: MoonIcon,
    auto: SunMoonIcon,
    coloured: SparklesIcon
  },
  sideMenu: {
    layoutGrid: LayoutGridIcon,
    userCog: UserCogIcon,
    userCheck: UserCheckIcon,
    warehouse: WarehouseIcon,
    store: StoreIcon,
    box: BoxIcon,
    share2: Share2Icon,
    package: PackageIcon,
    presentation: PresentationIcon,
    video: VideoIcon,
    users: UsersIcon,
    send: SendIcon,
    star: StarIcon,
    sliders: SlidersIcon,
    settings: SettingsIcon,
    fileText: FileTextIcon,
    feedback: ThumbsUp,
    aiBot: BotMessageSquare,
    // Report section
    lineChart: ChartLineIcon,
    barChart: ChartBarIcon,
    boxes: BoxesIcon,
    sparkles: SparklesIcon,

    // package: PackageIcon,
    rectangle: RectangleHorizontalIcon,
    packageOpen: PackageOpenIcon,
    slash: SlashIcon,
    sparkle: SparkleIcon,

    user: UserIcon,
    help: HelpCircleIcon,
    wandSparkles: WandSparklesIcon,
    wholeWord: WholeWordIcon,
    // Logout
    logout: LogOutIcon,
    maintenance: ServerCog
  },
  common: {
    menu: MenuIcon,
    key: KeyRound,
    search: SearchIcon,
    camera: CameraIcon,
    notification: BellIcon,
    heart: HeartIcon,
    truck: TruckIcon,
    shoppingBag: ShoppingBagIcon,
    info: InfoIcon,
    expand: ExpandIcon,
    plus: PlusIcon,
    minus: MinusIcon,
    previous: ChevronLeftIcon,
    next: ChevronRightIcon,
    column1: SquareIcon,
    column2: Columns2Icon,
    column3: Columns3Icon,
    column4: Columns4Icon,
    edit: PencilIcon,
    rotate: RotateCcwIcon,
    archive: ArchiveRestoreIcon,
    delete: TrashIcon,
    save: SaveIcon,
    history: HistoryIcon,
    copy: CopyIcon,
    notebookPen: NotebookPenIcon,
    penTool: PenToolIcon,
    threeDot: EllipsisVerticalIcon,
    gem: GemIcon,
    checkCheck: CheckCheckIcon,
    ruler: RulerIcon,
    import: ImportIcon,
    upload: UploadIcon,
    eye: EyeIcon,
    mail: MailIcon,
    filter: FunnelIcon,
    check: CheckIcon,
    sparkles: SparklesIcon,
    close: XIcon,
    image: ImagesIcon,
    rocket: RocketIcon,
    fileUp: FileUpIcon,
    mapPin: MapPinIcon,
    calendar: CalendarIcon,
    user: UserIcon,
    award: AwardIcon,
    trade: TrendingUpIcon,
    chartColumn: ChartColumnIcon,
    chartSpline: ChartSplineIcon,
    settings: SettingsIcon,
    userCheck: UserCheckIcon,
    userPlus: UserPlusIcon,
    userRoundX: UserRoundXIcon,
    userRoundCheck: UserRoundCheckIcon,
    userPen: UserPenIcon,
    left: ArrowLeft,
    packageCheck: PackageCheckIcon,
    share: Share2Icon,
    users: UsersIcon,
    trophy: TrophyIcon,
    download: DownloadIcon,
    message: MessageSquareText,
    ellipsis: EllipsisIcon,
    like: ThumbsUp,
    dislike: ThumbsDown,
    squarePen: SquarePen,
    indianRupee: IndianRupeeIcon,
    warehouse: WarehouseIcon,
    asterisk: AsteriskIcon
  },
  dashboard: {
    totalProduct: GemIcon,
    project: FolderOpenIcon,
    categories: SparkleIcon,
    video: VideoIcon,
    users: UsersRoundIcon,
    flower: FlowerIcon

  },
  reels: {
    play: PlayIcon,
    pause: PauseIcon,
  },
  sidemenu: {
    usersRound: UsersRoundIcon,
    folderOpen: FolderOpenIcon,
    brush: BrushIcon,
    chevronDown: ChevronDownIcon,
    logOut: LogOutIcon,
  },
  chevron: {
    leftIcon: ChevronLeftIcon,
    rightIcon: ChevronRightIcon,
    downIcon: ChevronDownIcon,
    upIcon: ChevronUpIcon,
  },
  share: {
    one: ShareIcon,
    two: Share2Icon,
  },
  product: {
    weight: WeightIcon,
    scale: ScaleIcon,
    flaskConical: FlaskConicalIcon,
    folderOpen: FolderOpenIcon,
    sparkle: SparkleIcon,
    star: StarIcon,
    binary: BinaryIcon,
    sticker: StickerIcon,
    hammer: HammerIcon,
    key: KeyIcon
  }
}
