# Generated by Django 6.0.2 on 2026-03-12 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productreview_review_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("secure_derma", "0003_alter_securedermaorder_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecureDermaCartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secure_derma_cart_items", to="product.product")),
                ("product_detail", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secure_derma_cart_items", to="product.productdetails")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secure_derma_cart_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "secure_derma_cart_items",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="securedermacartitem",
            constraint=models.UniqueConstraint(fields=("user", "product_detail"), name="unique_secure_derma_cart_item_per_user_detail"),
        ),
    ]
