# Generated by Django 6.0.2 on 2026-03-14 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_derma', '0004_securedermacartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securedermacartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
