# Generated by Django 6.0.2 on 2026-03-16 07:01

from django.db import migrations, models


ADD_SHIPPING_COLUMNS_SQL = """
ALTER TABLE secure_derma_orders
ADD COLUMN IF NOT EXISTS shipping_address varchar(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_city varchar(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_landmark varchar(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_name varchar(255) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_pincode varchar(10) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_state varchar(100) NOT NULL DEFAULT '',
ADD COLUMN IF NOT EXISTS shipping_provider varchar(100) NOT NULL DEFAULT '';
"""


DROP_SHIPPING_COLUMNS_SQL = """
ALTER TABLE secure_derma_orders
DROP COLUMN IF EXISTS shipping_state,
DROP COLUMN IF EXISTS shipping_pincode,
DROP COLUMN IF EXISTS shipping_name,
DROP COLUMN IF EXISTS shipping_landmark,
DROP COLUMN IF EXISTS shipping_provider,
DROP COLUMN IF EXISTS shipping_city,
DROP COLUMN IF EXISTS shipping_address;
"""


ADD_SHIPPING_PINCODE_INDEX_SQL = """
CREATE INDEX IF NOT EXISTS secure_derma_orders_shipping_pincode_idx
ON secure_derma_orders (shipping_pincode);
"""


DROP_SHIPPING_PINCODE_INDEX_SQL = """
DROP INDEX IF EXISTS secure_derma_orders_shipping_pincode_idx;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('secure_derma', '0006_securedermaorder_customer_address_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(ADD_SHIPPING_COLUMNS_SQL, DROP_SHIPPING_COLUMNS_SQL),
                migrations.RunSQL(ADD_SHIPPING_PINCODE_INDEX_SQL, DROP_SHIPPING_PINCODE_INDEX_SQL),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_address',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_city',
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_landmark',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_name',
                    field=models.CharField(blank=True, max_length=255),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_pincode',
                    field=models.CharField(blank=True, db_index=True, max_length=10),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_provider',
                    field=models.CharField(blank=True, max_length=100),
                ),
                migrations.AddField(
                    model_name='securedermaorder',
                    name='shipping_state',
                    field=models.CharField(blank=True, max_length=100),
                ),
            ],
        ),
    ]
