# Generated by Django 6.0.2 on 2026-03-29 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_derma', '0010_securedermavisit_device_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securedermavisit',
            new_name='secure_derm_path_9ce670_idx',
            old_name='secure_derm_path_d02346_idx',
        ),
        migrations.RenameIndex(
            model_name='securedermavisit',
            new_name='secure_derm_visitor_72b46c_idx',
            old_name='secure_derm_visitor_2d6d83_idx',
        ),
        migrations.AddIndex(
            model_name='securedermavisit',
            index=models.Index(fields=['device_type', 'created_at'], name='secure_derm_device__09f908_idx'),
        ),
    ]
